version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: moviemasti-db
    restart: always
    environment:
      MYSQL_DATABASE: MovieMasti
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_ROOT_PASSWORD: Bujji@192921
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moviemasti-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/MovieMasti?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Bujji@192921
    depends_on:
      - db

volumes:
  mysql_data:
